language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
