install:
    - gem install bundler
    - bundle --version
    - bundle install
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-19mode # JRuby in 1.9 mode
  - jruby
matrix:
  allow_failures:
